Repository USSF-ORBIT/ussf-portal-client, pull requests merged in 2021-08, with the labels that each got.

#62 build: Set up docker
  .dockerignore
  .env.local.template
  .envrc
  .github/workflows/cypress-ci.yml
  .github/workflows/node-ci.yml
  .gitignore
  .node-version
  Dockerfile
  README.md
  docker-compose.yml
  package.json
  yarn.lock
Labels: infrastructure, type: ci/cd

#99 ci: Updating dependabot. No package.json in /cypress and we don't want Node 16.
  .github/dependabot.yml
Labels: type: ci/cd

#102 ci: ignore 15-alpine and 16-alpine
  .github/dependabot.yml
Labels: type: ci/cd

#103 feat: Login page for MVP
  cypress/integration/mvp.spec.js
  public/img/ussf-logo-vert.svg
  src/__tests__/pages/login/index.test.tsx
  src/layout/MVP/DefaultLayout/DefaultLayout.tsx
  src/layout/MVP/LoginLayout/LoginLayout.module.scss
  src/layout/MVP/LoginLayout/LoginLayout.test.tsx
  src/layout/MVP/LoginLayout/LoginLayout.tsx
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/pages/login/login.module.scss
Labels: MVP

#105 feat: Login Notice page
  cypress/integration/mvp.spec.js
  src/__tests__/pages/login-notice.test.tsx
  src/pages/login-notice.tsx
  src/pages/login/login.module.scss
Labels: MVP, type: feature

#112 ci: Don't allow Dependabot to update between Major releases for NPM packages
  .github/dependabot.yml
Labels: type: ci/cd

#141 ci: Allow dependabot to manage all version updates, but auto-merge will only automate minor and patch versions.
  .github/dependabot.yml
  .github/workflows/merge-me.yml
Labels: type: ci/cd

#144 ci: reverting dependabot as automerge doesn't work with branch protections
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/merge-me.yml
Labels: type: ci/cd

#146 ci: Add cypress-axe tests and reports
  .github/workflows/cypress-ci.yml
  .gitignore
  cypress/integration/mvp.spec.js
  cypress/plugins/index.js
  cypress/plugins/logging.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: topic: testing

#149 chore(release): 1.0.0
  CHANGELOG.md
  package.json
Labels: MVP, type: release
