Repository USSF-ORBIT/ussf-portal-client, pull requests merged in 2021-11, with the labels that each got.

#293 feat: Sites & Applications UX fixes
  package.json
  src/components/AddWidget/AddWidget.module.scss
  src/components/Bookmark/Bookmark.module.scss
  src/components/Collection/Collection.module.scss
  src/components/Collection/Collection.stories.tsx
  src/components/CustomCollection/CustomCollection.module.scss
  src/components/CustomCollection/CustomCollection.stories.tsx
  src/components/CustomCollection/CustomCollection.tsx
  src/components/Footer/Footer.module.scss
  src/components/Header/Header.module.scss
  src/components/MySpace/MySpace.module.scss
  src/components/MySpace/MySpace.tsx
  src/components/Search/Search.module.scss
  src/components/SelectableCollection/SelectableCollection.stories.tsx
  src/layout/Beta/DefaultLayout/DefaultLayout.module.scss
  src/layout/Beta/DefaultLayout/DefaultLayout.tsx
  src/pages/beta/sites-and-applications.tsx
  src/stories/Typography.module.scss
  src/styles/pages/sitesAndApplications.module.scss
  yarn.lock
Labels: design, prototype, type: enhancement, type: storybook component, status: WIP, beta testing

#301 feat: Validate custom URL when adding a link to a collection
  cypress/integration/sites-and-applications.spec.js
  src/components/CustomCollection/CustomCollection.test.tsx
  src/components/CustomCollection/CustomCollection.tsx
Labels: prototype, type: enhancement, outcome: sites & applications

#306 fix: Unable to close out of flyout menu
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
Labels: prototype, mobile, type: bug

#303 ci: Adding AWS Actions
  .github/workflows/dev-aws-ecr.yml
  .github/workflows/prototype-aws-ecr.yml
Labels: type: ci/cd

#323 chore(deps): Major lib upgrades: NextJS, Keystone, GraphQL
  .gitignore
  cms.db
  next.config.js
  package.json
  schema.graphql
  schema.prisma
  src/__mocks__/.keystone/api.ts
  src/cms/schema.test.ts
  src/cms/schema.ts
  src/pages/beta/index.tsx
  src/pages/beta/sites-and-applications.tsx
  tsconfig.json
  yarn.lock
Labels: dependencies, type: chore, type: dependencies

#327 fix: Production Dockerfile
  Dockerfile
  cms.db
Labels: infrastructure, type: ci/cd, type: build

#317 chore(release): 2.0.0-alpha.0
  CHANGELOG.md
  package.json
Labels: prototype, type: release, outcome: sites & applications

#309 ci: Change tests and documentation to default to server, deprecate static site
  .envrc
  .github/workflows/cypress-ci.yml
  README.md
  cypress/integration/beta.spec.js
  docs/development.md
  package.json
  yarn.lock
Labels: type: documentation, type: ci/cd, outcome: sites & applications, static -> server

#296 dev: Set up SAML authentication flow with local test IdP
  Dockerfile
  Dockerfile.dev
  cypress/integration/saml.spec.js
  docker-compose.yml
  docs/development.md
  package.json
  src/lib/passport.ts
  src/lib/saml.ts
  src/pages/api/auth/[[...action]].ts
  users.php
  yarn.lock
Labels: priority: core functionality, type: feature, sessions, outcome: sites & applications, epic: SAML, dec. 20th

#347 fix: Updating `Trebuchet` to `Trebuchet MS`
  src/components/Header/Header.module.scss
  src/components/Search/Search.module.scss
  src/layout/Beta/DefaultLayout/DefaultLayout.module.scss
  src/stories/Typography.stories.tsx
Labels: design, priority: low, type: storybook component, topic: UX, beta testing, dec. 20th

#288 build: Add mongo and mongo-express to Dockerfile.dev
  docker-compose.yml
  docs/development.md
  mongo-init.js
  package.json
  yarn.lock
Labels: type: build

#361 ci(docker): Reduce size of Docker production image
  .dockerignore
  Dockerfile
Labels: infrastructure, type: ci/cd

#363 ci(cypress): Run Cypress CI against docker compose stack
  .github/workflows/cypress-ci.yml
  .github/workflows/node-ci.yml
  .gitignore
  cypress/fixtures/example.json
  docker-compose.e2e.yml
  docs/development.md
  e2e/.eslintrc.json
  e2e/cypress.json
  e2e/cypress/integration/beta.spec.js
  e2e/cypress/integration/mvp.spec.js
  e2e/cypress/integration/saml.spec.js
  e2e/cypress/integration/sites-and-applications.spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/plugins/logging.js
  e2e/cypress/support/commands.js
  e2e/cypress/support/index.js
  e2e/package.json
  e2e/yarn.lock
  jest.config.js
  package.json
  yarn.lock
Labels: type: ci/cd, portal database

#375 chore: Add Mallory & Noah as temporary codeowners
  .github/CODEOWNERS
Labels: type: chore

#366 chore: Add url descriptions
  cms.db
  e2e/cypress/integration/sites-and-applications.spec.js
Labels: type: chore, topic: cms, outcome: sites & applications, dec. 20th

#331 feat: SAML integration
  .envrc
  Dockerfile
  docker-compose.e2e.yml
  docker-compose.services.yml
  docs/development.md
  next.config.js
  src/lib/saml.ts
  src/lib/session.ts
  src/pages/api/auth/[[...action]].ts
Labels: type: feature, epic: SAML, dec. 20th

#374 feat: Apply default theme to beta pages & components
  public/assets/images/hero.jpeg
  src/__tests__/pages/beta/sites-and-applications.test.tsx
  src/components/AddWidget/AddWidget.module.scss
  src/components/AddWidget/AddWidget.stories.tsx
  src/components/AddWidget/AddWidget.tsx
  src/components/Bookmark/Bookmark.stories.tsx
  src/components/BookmarkList/BookmarkList.stories.tsx
  src/components/BookmarkList/BookmarkList.tsx
  src/components/Collection/Collection.stories.tsx
  src/components/CustomCollection/CustomCollection.module.scss
  src/components/CustomCollection/CustomCollection.stories.tsx
  src/components/CustomCollection/CustomCollection.tsx
  src/components/DropdownMenu/DropdownMenu.module.scss
  src/components/DropdownMenu/DropdownMenu.tsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.stories.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.stories.tsx
  src/components/MySpace/MySpace.stories.tsx
  src/components/PageHeader/PageHeader.module.scss
  src/components/PageHeader/PageHeader.stories.tsx
  src/components/PageHeader/PageHeader.tsx
  src/components/PageNav/PageNav.module.scss
  src/components/PageNav/PageNav.stories.tsx
  src/components/PageNav/PageNav.tsx
  src/components/PersonalData/PersonalData.module.scss
  src/components/PersonalData/PersonalData.stories.tsx
  src/components/PersonalData/PersonalData.test.tsx
  src/components/PersonalData/PersonalData.tsx
  src/components/Search/Search.module.scss
  src/components/Search/Search.stories.tsx
  src/components/Search/Search.tsx
  src/components/SelectableCollection/SelectableCollection.module.scss
  src/components/SelectableCollection/SelectableCollection.stories.tsx
  src/components/util/NavLink/NavLink.tsx
  src/layout/Beta/DefaultLayout/DefaultLayout.module.scss
  src/layout/Beta/DefaultLayout/DefaultLayout.tsx
  src/pages/_app.tsx
  src/pages/beta/sites-and-applications.tsx
  src/styles/pages/sitesAndApplications.module.scss
  src/styles/sfds/_colors.scss
  src/styles/sfds/_sfdsDependencies.scss
  src/styles/sfds/index.scss
Labels: design, type: feature, type: enhancement, type: storybook component, type: design assets, topic: design system, dec. 20th
