Repository USSF-ORBIT/ussf-portal-client, pull requests merged in 2021-12, with the labels that each got.

#383 feat: Add feedback card to sidebar
  src/components/FeedbackCard/FeedbackCard.module.scss
  src/components/FeedbackCard/FeedbackCard.stories.tsx
  src/components/FeedbackCard/FeedbackCard.tsx
  src/components/PageNav/PageNav.module.scss
  src/layout/Beta/DefaultLayout/DefaultLayout.test.tsx
  src/layout/Beta/DefaultLayout/DefaultLayout.tsx
  src/styles/sfds/index.scss
Labels: type: feature, type: storybook component, dec. 20th

#405 feat: Updated CMS content, footer nav links
  cms.db
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
Labels: type: feature, topic: cms, dec. 20th

#407 chore: Remove Noah and Mallory from CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore

#419 feat: Expire session cookie
  src/apolloClient.tsx
  src/lib/session.ts
  src/pages/api/graphql.tsx
Labels: type: security / ATO, sessions

#420 feat: Automatically add Example Collection to new users' My Space
  cms.db
  e2e/cypress/integration/sites-and-applications.spec.js
  schema.graphql
  schema.prisma
  src/__fixtures__/newPortalUser.ts
  src/cms/schema.ts
  src/models/User.test.ts
  src/models/User.ts
  src/pages/api/graphql.tsx
  src/pages/beta/sites-and-applications.tsx
Labels: type: feature, outcome: sites & applications, dec. 20th

#428 feat: Loading UI
  public/assets/images/rocket.png
  src/__tests__/pages/about-us/accomplishments.test.tsx
  src/__tests__/pages/about-us/index.test.tsx
  src/__tests__/pages/beta/index.test.tsx
  src/__tests__/pages/beta/sites-and-applications.test.tsx
  src/__tests__/pages/home/index.test.tsx
  src/__tests__/pages/news.test.tsx
  src/__tests__/pages/training-and-education/force-multiplier-program.test.tsx
  src/__tests__/pages/training-and-education/index.test.tsx
  src/components/CustomCollection/EditableCollectionTitle.tsx
  src/components/Loader.tsx
  src/components/Loader/Loader.module.scss
  src/components/Loader/Loader.stories.tsx
  src/components/Loader/Loader.test.tsx
  src/components/Loader/Loader.tsx
  src/components/LoadingWidget/LoadingWidget.module.scss
  src/components/LoadingWidget/LoadingWidget.stories.tsx
  src/components/LoadingWidget/LoadingWidget.tsx
  src/components/MySpace/MySpace.stories.tsx
  src/components/MySpace/MySpace.test.tsx
  src/components/MySpace/MySpace.tsx
  src/components/PersonalData/PersonalData.stories.tsx
  src/components/PersonalData/PersonalData.test.tsx
  src/components/PersonalData/PersonalData.tsx
  src/hooks/useUser.test.tsx
  src/hooks/useUser.ts
  src/pages/about-us/accomplishments.tsx
  src/pages/about-us/index.tsx
  src/pages/beta/index.tsx
  src/pages/beta/sites-and-applications.tsx
  src/pages/index.tsx
  src/pages/news.tsx
  src/pages/training-and-education/force-multiplier-program.tsx
  src/pages/training-and-education/index.tsx
Labels: design, type: feature, type: enhancement

#442 chore(deps): Update Next, dev packages
  next-env.d.ts
  package.json
  src/pages/api/graphql.tsx
  yarn.lock
Labels: dependencies, type: dependencies, dec. 20th

#441 dev: Set up server logging
  Dockerfile
  package.json
  server-preload.js
  yarn.lock
Labels: dec. 20th

#448 chore: Production readiness
  next.config.js
  src/pages/api/graphql.tsx
Labels: type: chore, dec. 20th

#440 feat: Make Join Beta UX discoverable on MVP site
  e2e/cypress/integration/beta.spec.js
  src/components/MVP/Header/Header.module.scss
  src/components/MVP/Header/Header.tsx
  src/components/modals/JoinBetaModal.tsx
  src/styles/sfds/index.scss
Labels: dec. 20th, do not merge

#455 chore(release): 2.0.0
  CHANGELOG.md
  package.json
Labels: type: release
