Repository USSF-ORBIT/ussf-portal-client, pull requests merged in 2021-07, with the labels that each got.

#5 chore: Config changes to get static build working
  .eslintrc.json
  .gitignore
  __mocks__/fileMock.js
  __tests__/pages/index.test.tsx
  components/Logo/Logo.tsx
  jest.config.js
  jest.setup.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/img/ussf-logo.svg
  tsconfig.json
  yarn.lock
Labels: type: chore

#23 chore: Add semantic PR workflow to lint PR titles
  .github/workflows/semantic-pr.yml
  README.md
Labels: type: ci/cd

#24 ci: Add required checks to `main` branch protection
  .github/settings.yml
Labels: type: ci/cd

#25 test: Add Cypress with basic home page test
  cypress.json
  cypress/.eslintrc.json
  cypress/fixtures/example.json
  cypress/integration/home.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  jest.config.js
  package.json
  yarn.lock
Labels: topic: testing, type: test coverage

#32 chore: Add dev commit type
  .github/workflows/semantic-pr.yml
  README.md
Labels: type: chore

#27 feat: Migrate `head` content, meta data from MVP site
  .env.local.template
  .eslintrc.json
  .gitignore
  README.md
  cypress/integration/home.spec.js
  pages/_app.tsx
  pages/index.tsx
  pages/test-page.tsx
  public/android-chrome-192x192.png
  public/android-chrome-256x256.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
Labels: type: feature

#30 dev: MVP Header component
  components/Logo/Logo.module.scss
  components/Logo/Logo.tsx
  components/MVP/Header/Header.module.scss
  components/MVP/Header/Header.stories.tsx
  components/MVP/Header/Header.test.tsx
  components/MVP/Header/Header.tsx
  package.json
  styles/_settings.scss
  styles/_uswdsDependencies.scss
  styles/index.scss
  styles/mvp/_external-link.scss
  styles/mvp/_global.scss
  styles/mvp/_mixins.scss
  styles/mvp/_settings.scss
  styles/mvp/_typography.scss
  styles/mvp/index.scss
  styles/settings.scss
  styles/storybook.scss
  yarn.lock
Labels: MVP, type: storybook component

#35 dev: MVP Footer & Identifier components
  components/MVP/Footer/Footer.module.scss
  components/MVP/Footer/Footer.stories.tsx
  components/MVP/Footer/Footer.test.tsx
  components/MVP/Footer/Footer.tsx
  components/MVP/Identifier/Identifier.stories.tsx
  components/MVP/Identifier/Identifier.test.tsx
  components/MVP/Identifier/Identifier.tsx
  public/img/linkedin.svg
Labels: MVP, type: storybook component

#37 feat: Default page layout
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  components/MVP/Footer/Footer.module.scss
  layout/MVP/DefaultLayout/DefaultLayout.module.scss
  layout/MVP/DefaultLayout/DefaultLayout.test.tsx
  layout/MVP/DefaultLayout/DefaultLayout.tsx
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/test-page.tsx
  scripts/copy_uswds_assets.sh
  styles/_settings.scss
  styles/mvp/_mixins.scss
  styles/storybook.scss
Labels: MVP, type: feature

#38 dev: MVP Announcement Card component
  public/img/bday.webp
  src/components/MVP/AnnouncementCard/AnnouncementCard.module.scss
  src/components/MVP/AnnouncementCard/AnnouncementCard.stories.tsx
  src/components/MVP/AnnouncementCard/AnnouncementCard.test.tsx
  src/components/MVP/AnnouncementCard/AnnouncementCard.tsx
  src/styles/mvp/_colors.scss
  src/styles/mvp/index.scss
Labels: MVP

#41 ci: Set up Cypress E2E tests in Github Actions
  .github/settings.yml
  .github/workflows/cypress-ci.yml
  .gitignore
  README.md
  cypress.json
  cypress/integration/home.spec.js
  package.json
  yarn.lock
Labels: topic: testing, type: ci/cd

#44 feat: About Us page
  cypress.json
  cypress/integration/mvp.spec.js
  public/img/launch.jpg
  src/__tests__/pages/about-us.test.tsx
  src/components/MVP/AnnouncementCard/AnnouncementCard.module.scss
  src/pages/about-us.tsx
  src/styles/mvp/_global.scss
  src/styles/mvp/_typography.scss
Labels: MVP, type: feature

#42 refactor: NavLink component
  package.json
  src/components/MVP/AnnouncementCard/AnnouncementCard.tsx
  src/components/MVP/Header/Header.test.tsx
  src/components/MVP/Header/Header.tsx
  src/components/util/LinkTo/LinkTo.tsx
  src/components/util/NavLink/NavLink.test.tsx
  src/components/util/NavLink/NavLink.tsx
  yarn.lock
Labels: type: refactor

#55 chore: Add Barry as a default codeowner
  .github/CODEOWNERS
Labels: type: chore

#46 feat: Accomplishments page
  cypress/integration/mvp.spec.js
  public/img/200326-F-KD758-1007.jpeg
  public/img/201020-X-MF529-0074.jpeg
  public/img/Security_Spaceforce_GettyImages-1189672147.jpeg
  public/img/hopkins-6-20.jpeg
  src/__tests__/pages/about-us/accomplishments.test.tsx
  src/__tests__/pages/about-us/index.test.tsx
  src/pages/about-us/accomplishments.tsx
  src/pages/about-us/index.tsx
  src/styles/mvp/_global.scss
  src/styles/mvp/_typography.scss
  src/styles/mvp/index.scss
Labels: MVP, type: feature

#52 feat: News page
  cypress/integration/mvp.spec.js
  src/__mocks__/news-rss.ts
  src/__tests__/pages/news.test.tsx
  src/pages/news.tsx
  src/styles/mvp/_global.scss
Labels: MVP, type: feature

#56 chore: Disable NextJS telemetry using env flag
  .env.local.template
  .github/workflows/cypress-ci.yml
Labels: type: chore
