Repository USSF-ORBIT/ussf-portal-client, pull requests merged in 2021-09, with the labels that each got.

#172 ci: Align Node versiona across repo and more Renovate tuning.
  .github/workflows/cypress-ci.yml
  .github/workflows/node-ci.yml
  .node-version
  Dockerfile
  package.json
  renovate.json
Labels: type: ci/cd

#183 refactor(storybook): Organize MVP components in Storybook
  next-env.d.ts
  src/components/MVP/AnnouncementCard/AnnouncementCard.stories.tsx
  src/components/MVP/CovidSiteAlert/CovidSiteAlert.stories.tsx
  src/components/MVP/Footer/Footer.stories.tsx
  src/components/MVP/Header/Header.stories.tsx
  src/components/MVP/Identifier/Identifier.stories.tsx
Labels: MVP, type: refactor, topic: storybook

#190 ci: ensuring 14.17.6 rather than 14.17.5 to make tests pass going forward
  .github/workflows/cypress-ci.yml
  .github/workflows/node-ci.yml
Labels: type: ci/cd

#201 dev: Bookmark component
  .storybook/preview.js
  jest.setup.js
  src/components/Bookmark/Bookmark.module.scss
  src/components/Bookmark/Bookmark.stories.tsx
  src/components/Bookmark/Bookmark.test.tsx
  src/components/Bookmark/Bookmark.tsx
  src/initIcons.ts
  src/pages/_app.tsx
  src/styles/_deps.scss
Labels: type: storybook component, outcome: sites & applications

#202 dev: Collection component
  src/components/Collection/Collection.module.scss
  src/components/Collection/Collection.stories.tsx
  src/components/Collection/Collection.test.tsx
  src/components/Collection/Collection.tsx
Labels: type: storybook component, outcome: sites & applications

#204 dev: Placeholder static data component
  src/components/PersonalData/PersonalData.module.scss
  src/components/PersonalData/PersonalData.stories.tsx
  src/components/PersonalData/PersonalData.test.tsx
  src/components/PersonalData/PersonalData.tsx
Labels: type: storybook component, outcome: sites & applications, beta testing

#205 ci: Set up workflow for Storybook Netlify branch deploy
  .github/workflows/storybook-branch.yml
Labels: type: storybook component

#203 dev: PageNav component
  src/components/PageNav/PageNav.stories.tsx
  src/components/PageNav/PageNav.test.tsx
  src/components/PageNav/PageNav.tsx
Labels: type: storybook component, outcome: sites & applications, beta testing

#214 dev: Header component
  public/img/ussf-logo-short.svg
  src/components/Header/Header.module.scss
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Logo/Logo.module.scss
  src/components/Logo/Logo.stories.tsx
  src/components/Logo/Logo.test.tsx
  src/components/Logo/Logo.tsx
Labels: type: storybook component, beta testing

#215 dev: Footer component
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.stories.tsx
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
Labels: type: storybook component, beta testing

#218 dev: Static Global Search component
  src/components/Search/Search.module.scss
  src/components/Search/Search.stories.tsx
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
Labels: type: storybook component

#219 feat: Layout for beta pages
  cypress/integration/beta.spec.js
  src/components/Footer/Footer.module.scss
  src/components/Header/Header.module.scss
  src/components/PageNav/PageNav.tsx
  src/components/PersonalData/PersonalData.tsx
  src/layout/Beta/DefaultLayout/DefaultLayout.module.scss
  src/layout/Beta/DefaultLayout/DefaultLayout.test.tsx
  src/layout/Beta/DefaultLayout/DefaultLayout.tsx
  src/pages/beta/index.tsx
  src/styles/index.scss
Labels: type: feature, outcome: sites & applications, beta testing

#222 ci: Add prototype branch deploys
  .github/workflows/storybook-branch.yml
  netlify.toml
Labels: prototype

#225 fix: Fix link color on home page
  next-env.d.ts
  src/pages/index.tsx
Labels: MVP, type: bug

#227 fix: Fix link color on home page
  CHANGELOG.md
  package.json
  src/pages/index.tsx
Labels: MVP, type: bug

#220 feat: Sites & Applications page
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierignore
  README.md
  cms.db
  cypress/integration/sites-and-applications.spec.js
  jest.config.js
  package.json
  src/__mocks__/.keystone/api.ts
  src/__tests__/pages/beta/sites-and-applications.test.tsx
  src/components/Bookmark/Bookmark.test.tsx
  src/components/Bookmark/Bookmark.tsx
  src/components/Collection/Collection.module.scss
  src/components/Footer/Footer.tsx
  src/layout/Beta/DefaultLayout/DefaultLayout.tsx
  src/pages/_app.tsx
  src/pages/beta/sites-and-applications.tsx
  src/styles/pages/sitesAndApplications.module.scss
  styles/mvp/_global.scss
Labels: prototype, type: feature, outcome: sites & applications, beta testing

#228 dev: BookmarkList component
  jest.config.js
  src/components/BookmarkList/BookmarkList.stories.tsx
  src/components/BookmarkList/BookmarkList.test.tsx
  src/components/BookmarkList/BookmarkList.tsx
  src/types/index.ts
Labels: type: storybook component, outcome: sites & applications

#223 docs: Add documentation for managing content
  README.md
  docs/cms.md
  docs/development.md
Labels: type: documentation, topic: cms, keystone (embed)

#231 feat: Sorting Sites & Applications
  .github/workflows/cypress-ci.yml
  cypress/integration/sites-and-applications.spec.js
  schema.graphql
  src/__mocks__/.keystone/api.ts
  src/__tests__/pages/beta/sites-and-applications.test.tsx
  src/cms/schema.ts
  src/components/BookmarkList/BookmarkList.test.tsx
  src/components/BookmarkList/BookmarkList.tsx
  src/components/Collection/Collection.stories.tsx
  src/components/Collection/Collection.test.tsx
  src/components/Collection/Collection.tsx
  src/initIcons.ts
  src/pages/beta/sites-and-applications.tsx
  src/styles/pages/sitesAndApplications.module.scss
  src/types/index.ts
Labels: prototype, type: feature, outcome: sites & applications

#240 feat: Update announcements on home page (#239)
  CHANGELOG.md
  package.json
  public/uploads/Guardian Ideal - FINAL - 1600 17Sept21.pdf
  public/uploads/US Space Force Enlisted Rank Insig Info Sheet (1).pdf
  src/__tests__/pages/home/index.test.tsx
  src/components/MVP/AnnouncementCard/AnnouncementCard.tsx
  src/pages/index.tsx
Labels: MVP, type: release

#243 feat: Delete link from custom collection
  cypress/integration/sites-and-applications.spec.js
  cypress/support/commands.js
  jest.config.js
  package.json
  src/apolloClient.tsx
  src/components/Collection/Collection.module.scss
  src/components/CustomCollection/CustomCollection.module.scss
  src/components/CustomCollection/CustomCollection.stories.tsx
  src/components/CustomCollection/CustomCollection.test.tsx
  src/components/CustomCollection/CustomCollection.tsx
  src/components/MySpace/MySpace.test.tsx
  src/components/MySpace/MySpace.tsx
  src/initIcons.ts
  src/operations/queries/getCollections.tsx
  src/operations/resolvers.tsx
  src/pages/beta/index.tsx
  src/schema.tsx
  src/types/index.ts
  yarn.lock
Labels: prototype, type: feature, type: storybook component, outcome: sites & applications
