Repository USSF-ORBIT/ussf-portal-client, pull requests merged in 2022-03, with the labels that each got.

#543 chore(release): 2.4.0
  CHANGELOG.md
  package.json
Labels: type: release

#562 chore(release): 2.5.0
  CHANGELOG.md
  package.json
Labels: type: release

#564 feat: Portal launch announcement & new grid
  .storybook/preview.js
  public/assets/images/launch_rocket.png
  src/__tests__/pages/beta/index.test.tsx
  src/components/AnnouncementLaunch/AnnouncementLaunch.module.scss
  src/components/AnnouncementLaunch/AnnouncementLaunch.stories.tsx
  src/components/AnnouncementLaunch/AnnouncementLaunch.tsx
  src/components/Footer/Footer.module.scss
  src/components/Header/Header.module.scss
  src/components/MySpace/MySpace.module.scss
  src/components/MySpace/MySpace.tsx
  src/components/PageHeader/PageHeader.tsx
  src/layout/Beta/DefaultLayout/DefaultLayout.tsx
  src/layout/Beta/DefaultLayout/PageLayout.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/beta/index.tsx
  src/pages/update-browser.tsx
  src/stories/grid.stories.tsx
  src/styles/_settings.scss
  src/styles/pages/home.module.scss
  src/styles/sfds/_grid.scss
  src/styles/sfds/_sfdsDependencies.scss
  src/styles/sfds/index.scss
Labels: type: storybook component

#571 chore: Update dependencies
  .github/workflows/codeql-analysis.yml
  .github/workflows/dev-aws-ecr.yml
  .github/workflows/node-ci.yml
  .storybook/preview-head.html
  docker-compose.client.yml
  docker-compose.cms.yml
  docker-compose.e2e.dev.yml
  docker-compose.e2e.yml
  docker-compose.services.yml
  package.json
  src/pages/api/bookmarks.ts
  src/pages/beta/index.tsx
  src/pages/beta/sites-and-applications.tsx
  yarn.lock
Labels: dependencies

#575 chore(release): 3.0.0
  CHANGELOG.md
  package.json
Labels: type: release
