Repository USSF-ORBIT/ussf-portal-client, pull requests merged in 2022-11, with the labels that each got.

#841 chore(deps): update amannn/action-semantic-pull-request action to v5 …
  .github/workflows/semantic-pr.yml
Labels: dependencies, github-actions

#829 build: migrate portal runner and e2e stages to distroless node
  Dockerfile
Labels: infrastructure, type: security / ATO

#853 chore: resolve apollo-server-core@3.11.1
  package.json
  yarn.lock
Labels: dependencies, type: security / ATO, needs: approval

#844 fix: design: dark mode improvements
  .storybook/preview-head.html
  src/components/BreadcrumbNav/BreadcrumbNav.module.scss
  src/components/BreadcrumbNav/BreadcrumbNav.stories.tsx
  src/components/BreadcrumbNav/BreadcrumbNav.tsx
  src/components/MySpace/MySpace.module.scss
  src/layout/DefaultLayout/DefaultLayout.module.scss
  src/styles/_themes.scss
  src/styles/index.scss
Labels: design, needs: feedback
