Repository USSF-ORBIT/ussf-portal-client, pull requests merged in 2023-12, with the labels that each got.

#1169 feat: Adds new graphql server for thirdparty api
  package.json
  src/__fixtures__/data/cmsInternalNewsArticle.ts
  src/pages/api/thirdparty/dataSources/thirdPartyKeystone.test.ts
  src/pages/api/thirdparty/dataSources/thirdPartyKeystone.ts
  src/pages/api/thirdparty/graphql.tsx
  src/pages/api/thirdparty/operations/getPublicArticles.ts
  src/pages/api/thirdparty/resolvers.test.ts
  src/pages/api/thirdparty/resolvers.ts
  src/pages/api/thirdparty/schema.ts
  yarn.lock
Labels: needs: 2 appeng approvals

#1174 chore(main): release 4.27.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1181 chore(main): release 4.28.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1180 fix(design): Footer Navigation + Layout enhancements
  src/components/FeedbackCard/FeedbackCard.test.tsx
  src/components/FeedbackCard/FeedbackCard.tsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/components/PageNav/PageNav.tsx
  src/layout/DefaultLayout/ArticleLayout.test.tsx
  src/layout/DefaultLayout/ArticleLayout.tsx
  src/layout/DefaultLayout/DefaultLayout.module.scss
  src/layout/DefaultLayout/DefaultLayout.test.tsx
  src/layout/DefaultLayout/DefaultLayout.tsx
  src/layout/DefaultLayout/PageLayout.test.tsx
  src/layout/DefaultLayout/PageLayout.tsx
  src/layout/ErrorLayout/ErrorLayout.test.tsx
  src/pages/landing/index.tsx
  src/pages/ussf-documentation.tsx
  src/styles/_govBanner.scss
  src/styles/_themes.scss
  src/styles/index.scss
Labels: design
